### ISSUE TITLE
black line around element on focus

### ISSUE THREAD

**Issue by matheusysd** [carolbezerra-dev/trybe-projects#1]
When we focus on elements it's common that appears a black line around them, sometimes it's become "_ugly_". To remove this we can use outline:none, see on this [video](https://www.loom.com/share/4af3c8bf618240c7b117daa5daf49207).

**Comment by carolbezerra-dev** [comment]
> When we focus on elements it's common that appears a black line around them, sometimes it's become "_ugly_". To remove this we can use outline:none, see on this [video](https://www.loom.com/share/4af3c8bf618240c7b117daa5daf49207).

I agree with you. I applied your suggestion and it looks much better now. Thanks for your help!
